sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js: 12
branches:
  only:
    - master
notifications:
  email: false
script:
  - npm run test
before_deploy:
  - npm run build
  - cd dist
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_API_TOKEN"
  skip_cleanup: true
  on:
    branch: release
