os: linux
language: node_js
cache:
  directories:
  - node_modules
node_js: 12
branches:
  only:
    - master
notifications:
  email: false
script:
  - npm run test
before_deploy:
  - npm run build
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_token: $NPM_API_TOKEN
  src: dist
  edge: true
  on:
    branch: master
